default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: register_development

test:
  <<: *default
  database: register_test

production:
  <<: *default
  database: register_production
  username: register
  password: <%= ENV['REGISTER_DATABASE_PASSWORD'] %>
